### ISSUE TITLE
datePickerView 设置最后的日期是当前日期，请问怎么设置？

### ISSUE THREAD

**Issue by ycywj** [duanhong169/PickerView#1]
datePickerView 设置最后的日期是当前日期，请问怎么设置？

**Comment by duanhong169** [comment]
抱歉，现在还不能支持设置结束时间，不过这确实是个需求，我会在近期实现！

**Comment by ycywj** [comment]
好的，谢谢，还有就是选择那儿，可不可以加个回调，比如用户手指停止滑动后回调一个方法来获取选中的数据，省市区选择器那儿是否可以隐藏区，只显示省和市？当然我提这些问题是希望能做得更完美，目前使用来看应该很好了。

**Comment by duanhong169** [comment]
意思是只在最后滚动结束的时候回调一次？隐藏区只显示省和市是个好建议，我考虑实现一下，感谢提出。

**Comment by ycywj** [comment]
是的哈，比如我滑动停止后，获取到数据要作一个什么样的操作，比如页面跳转啊，然后提交网络请求啊等等

**Comment by duanhong169** [comment]
OK

**Comment by duanhong169** [comment]
@ycywj 已支持设置截止时间:

```java
dateTimePickerView.setEndDate(Calendar.getInstance());
```

隐藏区：

```java
divisionPicker.setType(DivisionPickerView.TYPE_PROVINCE_AND_CITY);
```

或者xml指定`divisionPickerType`：

```xml
<top.defaults.view.DivisionPickerView
    android:id="@+id/divisionPicker"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:preferredMaxOffsetItemCount="4"
    app:divisionPickerType="provinceAndCity"
    android:background="#e7e7e7"/>
```

至于“用户手指停止滑动后回调”这个需求未实现，因为用户在滑动过程中如果稍微停顿，那么也会触发一次回调，仍然会回调多次，因此建议通过一个显式的动作来执行要触发的操作，比如通过按钮点击事件。

**Comment by huangqingfang** [comment]
0.3.1仓库失效了吗
