### ISSUE TITLE
请问有没有方法改变选择器的背景颜色呢？

### ISSUE THREAD

**Issue by PiterPeng** [duanhong169/PickerView#2]
项目主体风格是紫色，但背景一直是白色，这俩颜色放一起不美观呀

**Comment by duanhong169** [comment]
选择器本身就是一个View，可以直接设置背景颜色的。比如在xml里

    <top.defaults.view.PickerView
        android:id="@+id/pickerView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:isCyclic="false"
        android:background="#ff0000"/>
